import { test, expect } from '@playwright/test';
import { mockServices, signUp, answerQuestions, analysis } from './fixtures';

const sizes = [[360,800], [390,844], [412,915], [1280,720], [1440,900], [1920,1080]];
for (const [width,height] of sizes) test(`signup to calm home at ${width}x${height}`, async ({page}) => {
  await page.setViewportSize({width,height});
  await mockServices(page);
  await page.route('**/api/aim/cross-reference', route => route.fulfill({json: analysis}));
  await signUp(page);
  await expect(page.locator('#aim-onboarding-step-1')).toBeVisible();
  await expect(page.locator('#aim-primary-nav')).toHaveCount(0);
  await answerQuestions(page);
  await page.getByRole('button', {name:'Start here', exact:true}).click();
  await expect(page.locator('#calm-tour-heading')).toHaveText('This is Today.');
  await expect(page.locator('#calm-next-action')).toBeVisible();
  if (width === 390) await page.screenshot({path: 'test-results/calm-tour-mobile.png', fullPage:true});
  await page.getByRole('button', {name:'Next', exact:true}).click();
  await page.reload();
  await expect(page.locator('#calm-tour-heading')).toHaveText('Talk to AIM.');
  await page.getByRole('button', {name:'Next', exact:true}).click();
  await expect(page.locator('#calm-tour-heading')).toHaveText('Your check-in.');
  await page.getByRole('button', {name:'Ready', exact:true}).click();
  await expect(page.locator('#calm-tour-heading')).toHaveCount(0);
  await page.reload();
  await expect(page.getByTestId('next-move')).toHaveText('Call the training center');
  await expect(page.locator('#aim-primary-nav button')).toHaveCount(4);
  if (width === 390) await page.screenshot({path: 'test-results/calm-home-mobile.png', fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#nav-tab-more').click();
  for (const name of ['Projects','Goals','Wellness','Voice preferences','Profile','Google Drive','Coaches']) await expect(page.getByRole('button',{name,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Goals',exact:true}).click();
  await expect(page).toHaveURL(/#goals$/);
  await page.goBack();
  await expect(page.getByRole('heading',{name:'Your space'})).toBeVisible();
  await page.locator('#nav-tab-home').click();
  await page.locator('#nav-tab-life-update').click();
  await expect(page).toHaveURL(/#life-update$/);
  await expect(page.locator('textarea').first()).toBeVisible();
});

test('interrupted answers, unavailable voice/API, long input and tour save failure recover', async ({page}) => {
  await page.setViewportSize({width:360,height:800});
  await page.emulateMedia({reducedMotion:'reduce'});
  await mockServices(page);
  await page.addInitScript(() => { (window as any).SpeechRecognition = undefined; (window as any).webkitSpeechRecognition = undefined; });
  await signUp(page);
  await page.getByRole('button',{name:'Dictate with Voice'}).click();
  await expect(page.locator('#aim-current-state-textarea')).toBeEditable();
  await page.locator('#aim-current-state-textarea').fill('A long situation '.repeat(100));
  await page.reload();
  await expect(page.locator('#aim-current-state-textarea')).toHaveValue('A long situation '.repeat(100));
  await page.locator('#aim-onboarding-step-1 button[type=submit]').click();
  await page.reload();
  await expect(page.locator('#aim-onboarding-step-2')).toBeVisible();
  await page.locator('#aim-changes-wanted-textarea').fill('Find work');
  await page.locator('#aim-onboarding-step-2 button[type=submit]').click();
  await page.reload();
  await expect(page.locator('#aim-onboarding-step-3')).toBeVisible();
  await page.locator('#aim-desired-state-textarea').fill('Steady income');
  await page.locator('#aim-onboarding-step-3 button[type=submit]').click();
  await expect(page.getByText('AIM couldn’t build your plan right now. Your answers are saved. Please try again.')).toBeVisible();
  await expect(page.locator('#aim-desired-state-textarea')).toHaveValue('Steady income');
  await page.route('**/api/aim/cross-reference', route => route.fulfill({json: analysis}));
  await page.locator('#aim-onboarding-step-3 button[type=submit]').click();
  await page.getByRole('button',{name:'Start here',exact:true}).click();
  await page.evaluate(() => localStorage.setItem('test:save-fails','yes'));
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('tour progress couldn’t be saved');
  await expect(page.locator('#calm-tour-heading')).toHaveText('This is Today.');
  await page.evaluate(() => localStorage.removeItem('test:save-fails'));
  await page.getByRole('button',{name:'Skip tour',exact:true}).click();
  await page.reload();
  await expect(page.locator('#calm-tour-heading')).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const before = await page.locator('canvas').first().evaluate((el: HTMLCanvasElement) => el.toDataURL());
  await page.waitForTimeout(200);
  expect(await page.locator('canvas').first().evaluate((el: HTMLCanvasElement) => el.toDataURL())).toBe(before);
  await page.locator('#nav-tab-more').click();
  await page.getByRole('button',{name:'Account',exact:true}).click();
  await page.getByRole('button',{name:'Sign Out of Account'}).click();
  await expect(page.getByRole('button',{name:'Get started',exact:true})).toBeVisible();
  await signUp(page);
  await expect(page.getByTestId('next-move')).toHaveText('Call the training center');
  await expect(page.locator('#calm-tour-heading')).toHaveCount(0);
});
