// @ts-ignore Generated by the build step; it can be absent before a clean build.
import serverModule from '../dist/server.mjs';

const app = (serverModule as any).app ?? serverModule;
export default app;
