// @ts-expect-error Generated by the build step before Vercel packages the serverless function.
import serverModule from '../dist/server.mjs';

const app = (serverModule as any).app ?? serverModule;
export default app;
